### PR TITLE
Fancy figure and more

### PR DESCRIPTION
**Pull request by zmoon**
### What does your PR do?

Various changes. I can break this up into smaller if you are only interested in certain parts. Mostly I wanted to generate a figure of the colormaps broken down by category like on Crameri's website, so I added stuff related to that, also checking the categorization when loading the colormap data.

Summary:
* Use `ListedColormap` instead. Simpler and gives the same result for the non-categorical ones since they have N=256. This also addresses #7 since the colors can be recovered with `.colors`.
* Clean up the `.cm` namespace so that it is easier to use
* Fancier `show_cmaps` plotter, and show the result in the readme under its code demo.
* `show_cmaps` added to the top-level namespace
* `__all__` added to the top-level `__init__.py`
* In readme, import `cmcrameri.cm` as `cmc` for consistency with the `'cmc.<name>'` form for the registered cmaps added in #8 
* Add example of using a registered cmap name to the readme
* Running `cm.py` directly generates the `colormaps.png`
* Update the links to Crameri's website

#### Remaining

* [x] It would be nice to make the colormap terminology consistent (currently "colormap", "colour map", and "colourmap" depending on where you look). ~~Maybe use "colour map", since that is what Crameri uses.~~ Or "colormap" for consistency with Matplotlib.

### Testing

They currently pass. I could add more tests if you want.

colormaps

### CODE REVIEW

**Comment by callumrollo** [comment]
Great PR, thanks for your contributions! All the changes look good to me. Big improvement on the hacky original. I particularly like the use of asserts when categorizing colormaps.

I think standardising on "colormap" for consistency with matplotlib and other community colormaps like [cmocean](https://github.com/matplotlib/cmocean) would be a good idea. Once that's updated I'm happy to merge this in and do a release to get it on PyPI & conda-forge

**Comment by zmoon** [comment]
Also I noticed your `setup.py` has an out-of-date `download_url`. Maybe your open PR about build stuff addresses that though.

**Comment by zmoon** [comment]
@callumrollo thanks for creating this package! I hadn't seen these colormaps before stumbling upon it, cool stuff.

**Comment by callumrollo** [comment]
Yeah, I plan to automate the build process to fix these inconsistencies, but haven't got it quite figured out yet. I'll give that another crack when I have time.

**Comment by callumrollo** [comment]
Glad it's been useful to you! I saw Fabio's presentation on it at EGU a few years ago and offered to make a Python port. Didn't think it would get used this much tbh

**Comment by callumrollo** [comment]
I'm happy to merge this in if you like? I'll get the version numbers sorted in the next release, probably later this week.

**Pull request merged**
