### PR TITLE
add categorical maps files

### PR DESCRIPTION
**Pull request by FloLangenfeld**
Add the 16 categorical maps

### CODE REVIEW

**Comment by callumrollo** [comment]
Hi FloLangenfeld.

I opted not to include the categorical colormaps as they can be generated from the discrete palettes if a user wants them. Do you have a specific use case that requires the categorical colourmaps? Adding them will increase the size of the package and add some potentially confusing names to the colourmap namespace.

**Comment by FloLangenfeld** [comment]
Hello callumrollo,

It is mainly for consistency with other platforms/users; whether you are working with Matlab or R or python, the categorical maps should be the same and not depend on a potentially different reordering of the discrete palette (I wasn't able to find how to sort the discrete palletes in order to generate the categorical colormaps - I may have missed something here).
As for the size, the repository is currently 1.4Mb, which is rather lightwheighted, IMHO.

**Comment by callumrollo** [comment]
Thanks, I'll merge this in now. Will take a little while to propagate out to pip and conda-forge

**Comment by callumrollo** [comment]
@FloLangenfeld The new version is up on PyPI and conda-forge now. Thanks for your help

**Comment by FloLangenfeld** [comment]
Happy to contribute, @callumrollo !

PS: I promise, next time, I'll go through the tests as well. Sorry for the incovenience

**Pull request merged**
